name: Simple Command

on: 
  schedule:
      - cron: "30 * * * *"

  pull_request:

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "welcome"
      - name: multiline
        run: |
         node -v
         npm -v
