name: Simple Command

on: 
 repository_dispatch:
  types: [build]
  #schedule:
   #   - cron: "3 * * * *"

  pull_request:
   types: [closed,assigned,opened,reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "welcome"
      - name: multiline
        run: |
         node -v
         npm -v
